# Generated by Django 4.2.2 on 2024-01-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_orderupdates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderUpdates',
            new_name='OrderUpdate',
        ),
    ]
